"""Generate the static country name -> ISO3 mapping used at runtime.

This script uses hdx-python-country (a dev dependency) to produce the mapping
file at src/pydeflate/sources/_country_mapping.py.  Run it whenever upstream
data sources introduce new entity names.

Usage:
    uv run python scripts/generate_country_mapping.py
"""

from __future__ import annotations

from pathlib import Path

from hdx.location.country import Country
from imf_reader import weo
from oda_reader import download_dac1

OUTPUT = Path(__file__).resolve().parents[1] / "src" / "pydeflate" / "sources" / "_country_mapping.py"

# These are entity names that hdx-python-country cannot resolve or resolves
# incorrectly.  They are merged *after* the fuzzy lookup so they take priority.
OVERRIDES: dict[str, str] = {
    "World": "WLD",
    "European Union": "EU",
    "European Union (EU)": "EU",
    "Euro area": "EMU",
    "Euro Area (EA)": "EMU",
    "EU Institutions": "EUI",
    "DAC countries": "DAC",
    "DAC Countries, Total": "DAC",
    "Total DAC": "DAC",
    "Kosovo": "XXK",
    "Kosovo, Republic of": "XXK",
    "G7": "G7C",
    "Sub-Sahara Africa": "SSA",
    "Hong Kong Special Administrative Region, People's Republic of China": "HKG",
    "Macao Special Administrative Region, People's Republic of China": "MAC",
}

# Historical aliases — country names that appeared in older WEO/DAC releases
# but have since changed. Kept here so cached data from earlier downloads still
# resolves correctly.
HISTORICAL_ALIASES: dict[str, str] = {
    "Afghanistan": "AFG",
    "Swaziland": "SWZ",
    "Cape Verde": "CPV",
    "Congo, Dem. Rep.": "COD",
    "Congo, Democratic Republic of": "COD",
    "Congo, Republic of the": "COG",
    "Congo, Rep.": "COG",
    "Côte d'Ivoire": "CIV",
    "Ivory Coast": "CIV",
    "Czech Republic": "CZE",
    "Egypt": "EGY",
    "Egypt, Arab Rep.": "EGY",
    "Iran": "IRN",
    "Iran, Islamic Rep.": "IRN",
    "Korea, Rep.": "KOR",
    "Korea, South": "KOR",
    "South Korea": "KOR",
    "Kyrgyzstan": "KGZ",
    "Lao PDR": "LAO",
    "Laos": "LAO",
    "Macedonia, FYR": "MKD",
    "North Macedonia": "MKD",
    "Micronesia, Fed. Sts.": "FSM",
    "Burma": "MMR",
    "Slovak Republic": "SVK",
    "Slovakia": "SVK",
    "São Tomé and Príncipe": "STP",
    "Sao Tome and Principe": "STP",
    "East Timor": "TLS",
    "Turkey": "TUR",
    "Venezuela": "VEN",
    "Venezuela, RB": "VEN",
    "Vietnam": "VNM",
    "Viet Nam": "VNM",
    "Yemen": "YEM",
    "Yemen, Rep.": "YEM",
    "Gambia": "GMB",
    "Bahamas": "BHS",
    "Hong Kong SAR": "HKG",
    "Hong Kong SAR, China": "HKG",
    "Macao SAR": "MAC",
    "Macao SAR, China": "MAC",
    "Taiwan": "TWN",
    "Taiwan, China": "TWN",
    "West Bank and Gaza Strip": "PSE",
    "Palestinian Territory": "PSE",
}


def _collect_entity_names() -> set[str]:
    """Gather all unique entity name strings from IMF WEO and OECD DAC."""
    names: set[str] = set()

    # IMF WEO entity names
    print("Fetching IMF WEO data...")
    imf_df = weo.fetch_data()
    names.update(imf_df["REF_AREA_LABEL"].dropna().unique())

    # OECD DAC donor names
    print("Fetching OECD DAC data...")
    dac_df = download_dac1(
        filters={"measure": ["1010", "11010"], "flow_type": ["1140", "1160"]}
    )
    names.update(dac_df["donor_name"].dropna().unique())

    return names


def _build_mapping(names: set[str]) -> dict[str, str]:
    """Fuzzy-match each name to an ISO3 code, then apply overrides."""
    country = Country()
    mapping: dict[str, str] = {}

    for name in sorted(names):
        try:
            iso3 = country.get_iso3_country_code_fuzzy(name)[0]
        except Exception:
            iso3 = None

        if iso3 is not None:
            mapping[name] = iso3

    # Apply historical aliases (don't overwrite names from current data)
    for name, iso3 in HISTORICAL_ALIASES.items():
        mapping.setdefault(name, iso3)

    # Apply overrides (these win over fuzzy results)
    mapping.update(OVERRIDES)

    return dict(sorted(mapping.items()))


def _write_module(mapping: dict[str, str]) -> None:
    """Write the mapping as a Python module."""
    lines = [
        '# Auto-generated by scripts/generate_country_mapping.py',
        '# Do not edit manually — re-run the script to update.',
        '#',
        f'# Contains {len(mapping)} entries.',
        '',
        'COUNTRY_NAME_TO_ISO3: dict[str, str] = {',
    ]
    for name, iso3 in mapping.items():
        lines.append(f'    {name!r}: {iso3!r},')
    lines.append('}')
    lines.append('')  # trailing newline

    OUTPUT.write_text('\n'.join(lines))
    print(f"Wrote {len(mapping)} entries to {OUTPUT}")


def main() -> None:
    names = _collect_entity_names()
    print(f"Found {len(names)} unique entity names")
    mapping = _build_mapping(names)
    _write_module(mapping)


if __name__ == "__main__":
    main()
