name: Publish Documentation
on:
  push:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v2
      - uses: actions/checkout@master
        with:
          fetch-depth: 0
      - name: Build and Commit
        uses: sphinx-notes/pages@v2
        with:
          documentation_path: ./source
          requirements_path: ./requirements.txt

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages