name: Publish to PyPI

on:
  workflow_dispatch:

jobs:
  publish:
    name: Publish to PyPI
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-versions: ["3.10"]

    steps:
      - name: Check out the repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch all tags to enable dynamic versioning

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-versions }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry poetry-dynamic-versioning
          poetry self add poetry-dynamic-versioning  # Ensures it's enabled

      - name: Enable dynamic versioning
        run: poetry dynamic-versioning

      - name: Build the package
        run: poetry build

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@v1.10.3
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
          skip_existing: true
          verify_metadata: true